// <auto-generated />
using System;
using ItemCRUD.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItemCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItemCRUD.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BuyingUnit")
                        .HasColumnType("int");

                    b.Property<double?>("BuyingUnitPrice")
                        .HasColumnType("float");

                    b.Property<int?>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int?>("Department")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HSN")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SellingUnit")
                        .HasColumnType("int");

                    b.Property<double?>("SellingUnitPrice")
                        .HasColumnType("float");

                    b.Property<int?>("TaxId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ItemCRUD.Models.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CGST")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("IGST")
                        .HasColumnType("float");

                    b.Property<double?>("SGST")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("ItemCRUD.Models.Item", b =>
                {
                    b.HasOne("ItemCRUD.Models.Tax", null)
                        .WithMany("Items")
                        .HasForeignKey("TaxId");
                });

            modelBuilder.Entity("ItemCRUD.Models.Tax", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
